### ISSUE TITLE
404 at URL opened by :Gbrowse with visual selection on a repo with unpushed commits

### ISSUE THREAD

**Issue by katylava** [tpope/vim-rhubarb#18]
`:Gbrowse` without a visual selection uses the branch name in the URL, but with a visual selection it uses the commit hash. If the commit hasn't been pushed yet then I get a 404 page on Github. If I replace the hash in the URL with the branch name, then I get what I want.

Preferably it would use the branch name in the URL for visual selection too. Granted, since you have unpushed changes, it may not take you to the lines you expect, but that feels less broken than a 404. Or `:Gbrowse` could just be like "yo, you have unpushed commits, i don't know what you want to happen".

**Comment by tpope** [comment]
So the big problem isn't so much that the lines might not match up to what you expect (although that is a concern), but rather that including the branch name in the URL guarantees that the selected lines *will* be wrong at some point in the future for any actively developed project. These links often end up in issue trackers and other places that may serve as historical references, so I think changing the default would be doing a disservice to all of us in the future.

One workaround is to explicitly specify an upstream reference to be used to resolve the commit hash: `:.Gbrowse origin/master:%` or even `:Gbrowse origin:%`. One could make an argument that `:Gbrowse` with no arguments should have a similar default. I've resisted that thus far because it raises questions I'm not sure how to answer. Should `:Gbrowse master:%` use the local or remote commit? What about `:Gbrowse master~17:%`?

**Comment by katylava** [comment]
I see. That makes sense that it's not the default behavior. 

`:.Gbrowse origin/my-branch:%` is a little clunky, especially when I already tried it without arguments, got the 404, got confused, and only then realized I had unpushed commits.  It would be cool if `:Gbrowse` reminded me about the unpushed commits and didn't bother trying to open the location in my browser (or copy it to my clipboard if I use `!`).

Although, since it's separate from vim-fugitive now, maybe it doesn't know the branch status?

For context, I do `:gbr<tab>` as instinctively as any native vim command (thank you btw for creating such an integral part of my workflow) whenever I want to talk about some specific lines with a colleague. This happens most often when trying to get help while doing fast-paced debugging.

**Comment by tpope** [comment]
So figuring out what's upstream is actually pretty tricky. For a branch, we can look in `refs/remotes`, though that may be stale, and it would probably not be appropriate to call `git fetch`. For anything more complicated than a branch, it gets a lot harder. I decided that a consistent 404 was better than an error check that didn't always work. It's not nearly as self evident what went wrong, but I am trusting that's generally possible to reason backwards to it once you look at the URL. (Note all this logic lives on the Fugitive side of things, so it's not an issue from that perspective.)

I suppose I am open to changing the default of `:Gbrowse` to use the upstream commit. My followup questions can generally be answered with "no change", I think. I am less than enthused about trying to make that change in practice. I think I've narrowed down the relevant code to https://github.com/tpope/vim-fugitive/blob/fbf89773b4721ae5b46ccded0ceeee861921b697/plugin/fugitive.vim#L2285-L2312 but even then I might be mistaken. Basically `commit` needs to end up being the correct SHA, without breaking any of the other use cases.

**Comment by gregory** [comment]
@tpope what about listing the remotes in .git/config and prompt the user to pick the remote if there is more than 1 ?

**Comment by tpope** [comment]
Fugitive now finds the appropriate line range for the latest pushed commit.
