### ISSUE TITLE
Unknown function: netrw#NetrwBrowseX

### ISSUE THREAD

**Issue by Stanislav-Lapata** [tpope/vim-rhubarb#62]
When I run `:Gbrowse` I have error
```
E117: Unknown function: netrw#NetrwBrowseX 
```
vim-rhubarb version 
`5130596`

neovim version 
`NVIM v0.5.0-nightly-222-g35325ddac`

**Comment by VVKot** [comment]
Hey @tpope , thanks for an excellent plugin! Any thoughts on how to fix this one?

**Comment by idbrii** [comment]
This is likely a fugitive issue since rhubarb doesn't open the url, it just generates it. [fugitive uses :Browse or netrw to open it](https://github.com/tpope/vim-fugitive/blob/bebe504e38d0a20c30d6dd666c4c793b3cc66104/autoload/fugitive.vim#L5884-L5894).

Not sure if netrw is broken/removed on neovim. Or if you've somehow disabled it? You could install [tyru/open-browser.vim](https://github.com/tyru/open-browser.vim) and add a Browse command so Gbrowse will use it:

    command! -nargs=1 Browse OpenBrowser <args>

**Comment by tpope** [comment]
Can confirm Neovim still has netrw. From that dotfiles update I gather the issue is that it was disabled in favor of Dirvish.

**Comment by smarquez1** [comment]
This will also happen if you are using https://github.com/kyazdani42/nvim-tree.lua . 
`let g:nvim_tree_disable_netrw = 0` will make `:GBrowse` work correctly

**Comment by tpope** [comment]
I added a better error message if netrw is disabled. But why disable the autoload file? Disabling the plugin with `let g:loaded_netrwPlugin = 1` only seems to do the job just fine with no ill effects.

**Comment by sethidden** [comment]
In addition do idbrii's comment above, I had to do https://github.com/tyru/open-browser.vim/issues/98#issuecomment-317127504 on mac

Otherwise Gbrowse would open a browser tab only once
