### ISSUE TITLE
HomepageForUrl doesn't work with GitHub ssh subdomain and it breaks GBrowse

### ISSUE THREAD

**Issue by cacarrara** [tpope/vim-rhubarb#65]
**Problem:**

When I run `GBrowse` in some projects, it returns:
```
fugitive: No GBrowse handler installed for 'git@ssh.github.com:cacarrara/vimnimum.git'
```

**Previous investigation:**

Running `echo rhubarb#HomepageForUrl('git@ssh.github.com:cacarrara/vimnimum.git') ` it returns nothing. I suspect this is the problem. Even further, it seems the problem is the `ssh.` subdomain. Running the same function without `ssh.`: `echo rhubarb#HomepageForUrl('git@github.com:cacarrara/vimnimum.git') ` it properly returns the GitHub URL: `https://github.com/cacarrara/vimnimum`.

This is my git remote output:
```
git remote -v
origin  git@github.com:cacarrara/vimnimum.git (fetch)
origin  git@github.com:cacarrara/vimnimum.git (push)
```

I couldn't understand where `ssh.` subdomain comes from.

**Versions:**
- vim-fugitive (commit): 1c2663f
- vim-rhubarb (commit): 2590324

**Comment by tpope** [comment]
> I couldn't understand where `ssh.` subdomain comes from.

I don't understand this either. You're saying the `ssh.` does _not_ show up in `git remote -v` or `cat .git/config`, but it _does_ show up in the error message?

What is the output of `:echo FugitiveRemoteUrl()`?

**Comment by cacarrara** [comment]
> You're saying the ssh. does not show up in git remote -v or cat .git/config, but it does show up in the error message?

Exactly.

The outputs:
- git remote -v
```
origin  git@github.com:cacarrara/vimnimum.git (fetch)
origin  git@github.com:cacarrara/vimnimum.git (push)
```

- cat .git/config
```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = git@github.com:cacarrara/vimnimum.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
```
- :echo FugitiveRemoteUrl()
```
git@ssh.github.com:cacarrara/vimnimum.git  
```

As it can be seen, `FugitiveRemoteUrl` returns the remote URL with the ssh subdomain. :thinking:

**Comment by tpope** [comment]
Ohh check your `.ssh/config`, I bet you've got `ssh.github.com` in there.

**Comment by cacarrara** [comment]
Ah, you are absolutely right! My ssh config has:
```
Host github.com
  Hostname ssh.github.com
  Port 443
```

Maybe I've had done that, following this guide to [use ssh over HTTPs port](https://docs.github.com/en/github/authenticating-to-github/troubleshooting-ssh/using-ssh-over-the-https-port).

What's the best way to proceed here?

**Comment by tpope** [comment]
That automatic hostname substitution is a new feature in Fugitive. I was unaware of `ssh.github.com` and hadn't considered the possibility that people might alias `github.com` _to_ something, but it's easy enough to accommodate: just special case the domain and act accordingly.

But this is also uncovers a can of worms, which I want to go ahead and get on the record. Swapping out the hostname is good and sensible and supports real world use cases, but the fact we swap out *only* the hostname and not the port of for that matter the user leaves us in this weird in-between, where we can potentially end up pointing at the wrong destination. We could fix this for real SSH urls—`ssh://github.com/x` could become `ssh://ssh.github.com:443/x`—but we can't fix this for the `user@host:path` syntax because that syntax does not accept a port. I think my short term fix will be to support port and user where possible, and my long term fix will be to transition away from using the URL as an intermediary, which also save the trouble of parsing them later.
